# A sample Gemfile
source "https://rubygems.org"

gem 'mining_depot', path: '../../mining_depot'
gem 'json', '> 1.8.1'
gem 'curses' if RUBY_VERSION >= '2.1'

# for development, etc.
gem 'rubocop'
gem 'pry'
